# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk15

services:
  - postgresql

before_install:
  - psql -c 'create database rabbit;' -U postgres
  -
# используем режим обычного пользователя для сборки проекта.
sudo: false

env:
  global:
    - CODECOV_TOKEN="90a1faec-71c7-4eae-b787-8a0deaa5c1b0"

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почтуyouremail@smtp.ru(Изменить на свою) если сборка упала
notifications:
  email:
    recipients:
      - selesitomorozov@gmail.com
    on_success: never # default: change
    on_failure: always # default: always